# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reportAt', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=5, null=True)),
                ('seqno', models.IntegerField(blank=True, null=True)),
                ('rsrp', models.FloatField(blank=True, null=True)),
                ('sinr', models.FloatField(blank=True, null=True)),
                ('temper', models.FloatField(blank=True, null=True)),
                ('damp', models.FloatField(blank=True, null=True)),
                ('light', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('buttery', models.IntegerField(blank=True, null=True)),
                ('led', models.CharField(blank=True, max_length=5, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviceEui', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('led', models.CharField(blank=True, max_length=5, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terminal',
            },
        ),
        migrations.CreateModel(
            name='TerminalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayEui', models.CharField(max_length=20)),
                ('deviceEui', models.CharField(max_length=20)),
                ('led', models.CharField(max_length=5)),
                ('createAt', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ok', 'Ok')], default='Pending', max_length=10)),
            ],
            options={
                'db_table': 'terminal_message',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('displayName', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AlterUniqueTogether(
            name='terminalmessage',
            unique_together=set([('deviceEui', 'createAt')]),
        ),
        migrations.AddField(
            model_name='terminal',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensorApp.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='deviceEui',
            field=models.ForeignKey(db_column='deviceEui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sensorApp.Terminal', to_field='deviceEui'),
        ),
    ]
